
apiVersion: v1
kind: Service
metadata:
  name: video-backend-service
  labels:
    app: elefanti-video-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: elefanti-video-backend
